export const CHAR = {
  ARROW_DOWN: '⬇️',
  ARROW_UP: '⬆️',
  ARROW_LEFT: '⬅️',
  ARROW_RIGHT: '➡️',
  DARROW_DOWN: '⇩',
  DARROW_UP: '⇧',
  DARROW_LEFT: '⇦',
  DARROW_RIGHT: '⇨',
  DOT_GREEN: '🟢',
  DOT_RED: '🔴',
  BALANCE: '⚖️',
  BITCOIN: '₿',
  COIN: '🪙',
  CHART_UP: '📈',
  CHART_DOWN: '📉',
  CHART_YEN: '💹',
  CURRENCY: '💱',
  DOLLAR: '💲',
  EXCHANGE: '💱',
  HANDLE: '=',
  LIGHTNING: '⚡',
  LINK: '🔗',
  RED_X: '❌',
  CHECKMARK: '✅',
  WARNING: '⚠️',
  HAPPY: '😃',
}

export default CHAR